name: time-varying-rhgs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas # for plotly
  - plotly
  - matplotlib
  - conda-forge::cvxpy
  - conda-forge::casadi
  - MOSEK::mosek
  - conda-forge::jupyterlab
  - ipywidgets
  - nbconvert
  - nbformat
  - tqdm